-- Spring Batch 메타데이터 시퀀스 생성 (SC_PT 스키마)
-- Oracle DB에서 실행

-- BATCH_STEP_EXECUTION_SEQ 시퀀스
CREATE SEQUENCE SC_PT.BATCH_STEP_EXECUTION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- BATCH_JOB_EXECUTION_SEQ 시퀀스
CREATE SEQUENCE SC_PT.BATCH_JOB_EXECUTION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- BATCH_JOB_EXECUTION_PARAMS_SEQ 시퀀스
CREATE SEQUENCE SC_PT.BATCH_JOB_EXECUTION_PARAMS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE; 